const gets = {
	'/mqsasdata/getExceptionlvpkn.do':   	'getExceptionlvpkn',
	'/mqsasdata/getDropframelvpkn.do':   	'getDropframelvpkn',
	'/mqsas/mqsasDropFrame.do':   	'mqsasDropFrame',
	'/test1/test':   	'test',
	'/mqsas/startTime/getAvgStartTime.do':   	'adTest',
	'/mqsas/test1':   	'test',
	'/mqsas/performance/dropFrame/ringCmp.do':   	'ringCmp',
	'/mqsas/performance/dropFrame/allStatus.do':   	'allStatus',
	'/mqsas/performance/dropFrame/screenAllStatus.do':   	'allStatus',
	'/mqsas/performance/dropFrame/trend.do':   	'trend',
	'/knowledge/queryAllError.do':   	'queryAllError',
	'/mqsasABTest/getAllModels.do':   	'getAllModels',
	'/mqsasABTest/createPermit.do':   	'createPermit',
	'/knowledge/searchInfoIdMsg.do':   	'searchInfoIdMsg',
	'/mqsasdata/getThermalalllv.do':   	'getThermalalllv',
	'/mqsas/thermalRatio.do':   	'thermalRatios',
	'/mqsasABTest/selectCase.do':  	'selectCase',
	'/mqsas/excp/dashboard/summary.do':  	'getComparedData',
	'/mqsasABTest/uploadImeis.do':  	'uploadImeis',
	'/mqsasdata/getDropframevpknByl.do':   	'getDropframevpknByl',
	'/mqsas/excp/details.do':   	'excpDetails',
	'/mqsasback/getRedisVal.do':  	'getRedisVal',
	'/mqsas/caton/app/getApp.do':  	'catonAppGetApp',
	'/mqsas/caton/app/getWindow.do':  	'catonAppGetWindow',
	'/mqsas/caton/app/getCause.do':  	'catonAppGetCause',
	'/mqsas/caton/app/getVersions.do':  	'catonAppGetCause',
	'/mqsas/excp/dashboard/allVersion.do':  	'allVersion',
	'/mqsas/excp/dashboard/bigCategory.do':   	'bigCategory',
	'/mqsas/caton/app/getSysCause.do':  	'catonAppGetCause',
	'/mqsas/startTime/getWhiteList.do':   	'getWhiteListVersion',
	'/mqsas/successRatetest':   	'successRatetest',
	'/mqsas/successRateVersion':  	'successRateVersion',
	'/mqsas/otatime/getUpdateRate.do':   	'getUpdateRate',
	'/mqsas/excp//dashboard/allVersion.do':   	'allVersion',
	'/mqsas/fluency/getFluencyByVersion.do':   	'getFluencyByVersion',
	'/mqsas/fluency/getFluencyByModel.do':   	'getFluencyByModel',
	'/mqsas/caton/app/defaultStatus.do':   	'defaultStatus',
	'/mqsas/excp/getPkns.do':   	'getPkns',
	'/mqsas/excp/dashboard/category.do':   	'category',
	'/mqsasdata/getUsefullVersion.do':  	'getUsefullVersion',
	'/mqsas/performance/dropFrame/avgCaton.do':  	'avgCaton',
	'/whiteList/showAll/mqsas.do':   	'whiteListshowAll',
	'/mqsas/excp/list.do':'excpList',
	'/mqsas/excp/dashboard/topkcases.do': 'topkcases'
}

module.exports =  gets;